excluded:
  - Pods
  - DesafioCIANDT/Resources/R.generated.swift
  - DesafioCIANDTTests

line_length:
  warning: 165
  ignores_comments: true
  ignores_function_declarations: true

mark:
  severity: error

vertical_whitespace:
  severity: error

type_name:
  max_length: 60
  excluded:
    - T
    - U
